// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shared/proto/order_service/kafka.proto

package order_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TaxiType      TaxiType               `protobuf:"varint,3,opt,name=taxi_type,json=taxiType,proto3,enum=order.v1.TaxiType" json:"taxi_type,omitempty"`
	Pickup        *Location              `protobuf:"bytes,4,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Destination   *Location              `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=order.v1.Status" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedEvent) Reset() {
	*x = OrderCreatedEvent{}
	mi := &file_shared_proto_order_service_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedEvent) ProtoMessage() {}

func (x *OrderCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedEvent.ProtoReflect.Descriptor instead.
func (*OrderCreatedEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreatedEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreatedEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreatedEvent) GetTaxiType() TaxiType {
	if x != nil {
		return x.TaxiType
	}
	return TaxiType_TAXI_TYPE_UNSPECIFIED
}

func (x *OrderCreatedEvent) GetPickup() *Location {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *OrderCreatedEvent) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *OrderCreatedEvent) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *OrderCreatedEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_shared_proto_order_service_kafka_proto protoreflect.FileDescriptor

const file_shared_proto_order_service_kafka_proto_rawDesc = "" +
	"\n" +
	"&shared/proto/order_service/kafka.proto\x12\x0eorder.kafka.v1\x1a.shared/proto/order_service/order_service.proto\"\xa3\x02\n" +
	"\x11OrderCreatedEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\ttaxi_type\x18\x03 \x01(\x0e2\x12.order.v1.TaxiTypeR\btaxiType\x12*\n" +
	"\x06pickup\x18\x04 \x01(\v2\x12.order.v1.LocationR\x06pickup\x124\n" +
	"\vdestination\x18\x05 \x01(\v2\x12.order.v1.LocationR\vdestination\x12(\n" +
	"\x06status\x18\x06 \x01(\x0e2\x10.order.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAtBUZSgithub.com/aleksiaichuk-innowise/inno_taxi/shared/proto/order_service;order_serviceb\x06proto3"

var (
	file_shared_proto_order_service_kafka_proto_rawDescOnce sync.Once
	file_shared_proto_order_service_kafka_proto_rawDescData []byte
)

func file_shared_proto_order_service_kafka_proto_rawDescGZIP() []byte {
	file_shared_proto_order_service_kafka_proto_rawDescOnce.Do(func() {
		file_shared_proto_order_service_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_kafka_proto_rawDesc), len(file_shared_proto_order_service_kafka_proto_rawDesc)))
	})
	return file_shared_proto_order_service_kafka_proto_rawDescData
}

var file_shared_proto_order_service_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_proto_order_service_kafka_proto_goTypes = []any{
	(*OrderCreatedEvent)(nil), // 0: order.kafka.v1.OrderCreatedEvent
	(TaxiType)(0),             // 1: order.v1.TaxiType
	(*Location)(nil),          // 2: order.v1.Location
	(Status)(0),               // 3: order.v1.Status
}
var file_shared_proto_order_service_kafka_proto_depIdxs = []int32{
	1, // 0: order.kafka.v1.OrderCreatedEvent.taxi_type:type_name -> order.v1.TaxiType
	2, // 1: order.kafka.v1.OrderCreatedEvent.pickup:type_name -> order.v1.Location
	2, // 2: order.kafka.v1.OrderCreatedEvent.destination:type_name -> order.v1.Location
	3, // 3: order.kafka.v1.OrderCreatedEvent.status:type_name -> order.v1.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_shared_proto_order_service_kafka_proto_init() }
func file_shared_proto_order_service_kafka_proto_init() {
	if File_shared_proto_order_service_kafka_proto != nil {
		return
	}
	file_shared_proto_order_service_order_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_kafka_proto_rawDesc), len(file_shared_proto_order_service_kafka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_order_service_kafka_proto_goTypes,
		DependencyIndexes: file_shared_proto_order_service_kafka_proto_depIdxs,
		MessageInfos:      file_shared_proto_order_service_kafka_proto_msgTypes,
	}.Build()
	File_shared_proto_order_service_kafka_proto = out.File
	file_shared_proto_order_service_kafka_proto_goTypes = nil
	file_shared_proto_order_service_kafka_proto_depIdxs = nil
}
