// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shared/proto/order_service/order_service.proto

package order_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaxiType int32

const (
	TaxiType_TAXI_TYPE_UNSPECIFIED TaxiType = 0
	TaxiType_TAXI_TYPE_ECONOMY     TaxiType = 1
	TaxiType_TAXI_TYPE_COMFORT     TaxiType = 2
	TaxiType_TAXI_TYPE_BUSINESS    TaxiType = 3
)

// Enum value maps for TaxiType.
var (
	TaxiType_name = map[int32]string{
		0: "TAXI_TYPE_UNSPECIFIED",
		1: "TAXI_TYPE_ECONOMY",
		2: "TAXI_TYPE_COMFORT",
		3: "TAXI_TYPE_BUSINESS",
	}
	TaxiType_value = map[string]int32{
		"TAXI_TYPE_UNSPECIFIED": 0,
		"TAXI_TYPE_ECONOMY":     1,
		"TAXI_TYPE_COMFORT":     2,
		"TAXI_TYPE_BUSINESS":    3,
	}
)

func (x TaxiType) Enum() *TaxiType {
	p := new(TaxiType)
	*p = x
	return p
}

func (x TaxiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxiType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_order_service_order_service_proto_enumTypes[0].Descriptor()
}

func (TaxiType) Type() protoreflect.EnumType {
	return &file_shared_proto_order_service_order_service_proto_enumTypes[0]
}

func (x TaxiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxiType.Descriptor instead.
func (TaxiType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED     Status = 0
	Status_STATUS_CREATED         Status = 1
	Status_STATUS_DRIVER_ASSIGNED Status = 2
	Status_STATUS_IN_PROGRESS     Status = 3
	Status_STATUS_COMPLETED       Status = 4
	Status_STATUS_CANCELLED       Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CREATED",
		2: "STATUS_DRIVER_ASSIGNED",
		3: "STATUS_IN_PROGRESS",
		4: "STATUS_COMPLETED",
		5: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":     0,
		"STATUS_CREATED":         1,
		"STATUS_DRIVER_ASSIGNED": 2,
		"STATUS_IN_PROGRESS":     3,
		"STATUS_COMPLETED":       4,
		"STATUS_CANCELLED":       5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_order_service_order_service_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_shared_proto_order_service_order_service_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{1}
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiType      TaxiType               `protobuf:"varint,1,opt,name=taxi_type,json=taxiType,proto3,enum=order.v1.TaxiType" json:"taxi_type,omitempty"`
	Start         *Location              `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Destination   *Location              `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetTaxiType() TaxiType {
	if x != nil {
		return x.TaxiType
	}
	return TaxiType_TAXI_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CreateOrderRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TaxiType      TaxiType               `protobuf:"varint,4,opt,name=taxi_type,json=taxiType,proto3,enum=order.v1.TaxiType" json:"taxi_type,omitempty"`
	Start         *Location              `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Destination   *Location              `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.Status" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Order) GetTaxiType() TaxiType {
	if x != nil {
		return x.TaxiType
	}
	return TaxiType_TAXI_TYPE_UNSPECIFIED
}

func (x *Order) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Order) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Order) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

var File_shared_proto_order_service_order_service_proto protoreflect.FileDescriptor

const file_shared_proto_order_service_order_service_proto_rawDesc = "" +
	"\n" +
	".shared/proto/order_service/order_service.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"\xa5\x01\n" +
	"\x12CreateOrderRequest\x12/\n" +
	"\ttaxi_type\x18\x01 \x01(\x0e2\x12.order.v1.TaxiTypeR\btaxiType\x12(\n" +
	"\x05start\x18\x02 \x01(\v2\x12.order.v1.LocationR\x05start\x124\n" +
	"\vdestination\x18\x03 \x01(\v2\x12.order.v1.LocationR\vdestination\"\xbd\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12/\n" +
	"\ttaxi_type\x18\x04 \x01(\x0e2\x12.order.v1.TaxiTypeR\btaxiType\x12(\n" +
	"\x05start\x18\x05 \x01(\v2\x12.order.v1.LocationR\x05start\x124\n" +
	"\vdestination\x18\x06 \x01(\v2\x12.order.v1.LocationR\vdestination\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.order.v1.StatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"<\n" +
	"\x13CreateOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"0\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x02 \x01(\x01R\x04long*k\n" +
	"\bTaxiType\x12\x19\n" +
	"\x15TAXI_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TAXI_TYPE_ECONOMY\x10\x01\x12\x15\n" +
	"\x11TAXI_TYPE_COMFORT\x10\x02\x12\x16\n" +
	"\x12TAXI_TYPE_BUSINESS\x10\x03*\x94\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CREATED\x10\x01\x12\x1a\n" +
	"\x16STATUS_DRIVER_ASSIGNED\x10\x02\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x03\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x052q\n" +
	"\fOrderService\x12a\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/ordersBUZSgithub.com/aleksiaichuk-innowise/inno_taxi/shared/proto/order_service;order_serviceb\x06proto3"

var (
	file_shared_proto_order_service_order_service_proto_rawDescOnce sync.Once
	file_shared_proto_order_service_order_service_proto_rawDescData []byte
)

func file_shared_proto_order_service_order_service_proto_rawDescGZIP() []byte {
	file_shared_proto_order_service_order_service_proto_rawDescOnce.Do(func() {
		file_shared_proto_order_service_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_order_service_proto_rawDesc), len(file_shared_proto_order_service_order_service_proto_rawDesc)))
	})
	return file_shared_proto_order_service_order_service_proto_rawDescData
}

var file_shared_proto_order_service_order_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_proto_order_service_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shared_proto_order_service_order_service_proto_goTypes = []any{
	(TaxiType)(0),               // 0: order.v1.TaxiType
	(Status)(0),                 // 1: order.v1.Status
	(*CreateOrderRequest)(nil),  // 2: order.v1.CreateOrderRequest
	(*Order)(nil),               // 3: order.v1.Order
	(*CreateOrderResponse)(nil), // 4: order.v1.CreateOrderResponse
	(*Location)(nil),            // 5: order.v1.Location
}
var file_shared_proto_order_service_order_service_proto_depIdxs = []int32{
	0, // 0: order.v1.CreateOrderRequest.taxi_type:type_name -> order.v1.TaxiType
	5, // 1: order.v1.CreateOrderRequest.start:type_name -> order.v1.Location
	5, // 2: order.v1.CreateOrderRequest.destination:type_name -> order.v1.Location
	0, // 3: order.v1.Order.taxi_type:type_name -> order.v1.TaxiType
	5, // 4: order.v1.Order.start:type_name -> order.v1.Location
	5, // 5: order.v1.Order.destination:type_name -> order.v1.Location
	1, // 6: order.v1.Order.status:type_name -> order.v1.Status
	3, // 7: order.v1.CreateOrderResponse.order:type_name -> order.v1.Order
	2, // 8: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	4, // 9: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_shared_proto_order_service_order_service_proto_init() }
func file_shared_proto_order_service_order_service_proto_init() {
	if File_shared_proto_order_service_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_order_service_proto_rawDesc), len(file_shared_proto_order_service_order_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_order_service_order_service_proto_goTypes,
		DependencyIndexes: file_shared_proto_order_service_order_service_proto_depIdxs,
		EnumInfos:         file_shared_proto_order_service_order_service_proto_enumTypes,
		MessageInfos:      file_shared_proto_order_service_order_service_proto_msgTypes,
	}.Build()
	File_shared_proto_order_service_order_service_proto = out.File
	file_shared_proto_order_service_order_service_proto_goTypes = nil
	file_shared_proto_order_service_order_service_proto_depIdxs = nil
}
