// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shared/proto/order_service/order_service.proto

package order_service

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaxiType int32

const (
	TaxiType_TAXI_TYPE_UNSPECIFIED TaxiType = 0
	TaxiType_TAXI_TYPE_ECONOMY     TaxiType = 1
	TaxiType_TAXI_TYPE_COMFORT     TaxiType = 2
	TaxiType_TAXI_TYPE_BUSINESS    TaxiType = 3
)

// Enum value maps for TaxiType.
var (
	TaxiType_name = map[int32]string{
		0: "TAXI_TYPE_UNSPECIFIED",
		1: "TAXI_TYPE_ECONOMY",
		2: "TAXI_TYPE_COMFORT",
		3: "TAXI_TYPE_BUSINESS",
	}
	TaxiType_value = map[string]int32{
		"TAXI_TYPE_UNSPECIFIED": 0,
		"TAXI_TYPE_ECONOMY":     1,
		"TAXI_TYPE_COMFORT":     2,
		"TAXI_TYPE_BUSINESS":    3,
	}
)

func (x TaxiType) Enum() *TaxiType {
	p := new(TaxiType)
	*p = x
	return p
}

func (x TaxiType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaxiType) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_order_service_order_service_proto_enumTypes[0].Descriptor()
}

func (TaxiType) Type() protoreflect.EnumType {
	return &file_shared_proto_order_service_order_service_proto_enumTypes[0]
}

func (x TaxiType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaxiType.Descriptor instead.
func (TaxiType) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED     Status = 0
	Status_STATUS_CREATED         Status = 1
	Status_STATUS_DRIVER_ASSIGNED Status = 2
	Status_STATUS_IN_PROGRESS     Status = 3
	Status_STATUS_COMPLETED       Status = 4
	Status_STATUS_CANCELLED       Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CREATED",
		2: "STATUS_DRIVER_ASSIGNED",
		3: "STATUS_IN_PROGRESS",
		4: "STATUS_COMPLETED",
		5: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":     0,
		"STATUS_CREATED":         1,
		"STATUS_DRIVER_ASSIGNED": 2,
		"STATUS_IN_PROGRESS":     3,
		"STATUS_COMPLETED":       4,
		"STATUS_CANCELLED":       5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_shared_proto_order_service_order_service_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_shared_proto_order_service_order_service_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{1}
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxiType      TaxiType               `protobuf:"varint,1,opt,name=taxi_type,json=taxiType,proto3,enum=order.v1.TaxiType" json:"taxi_type,omitempty"`
	Start         *Location              `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Destination   *Location              `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetTaxiType() TaxiType {
	if x != nil {
		return x.TaxiType
	}
	return TaxiType_TAXI_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *CreateOrderRequest) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DriverId        string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TaxiType        TaxiType               `protobuf:"varint,4,opt,name=taxi_type,json=taxiType,proto3,enum=order.v1.TaxiType" json:"taxi_type,omitempty"`
	Start           *Location              `protobuf:"bytes,5,opt,name=start,proto3" json:"start,omitempty"`
	Destination     *Location              `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Status          Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.Status" json:"status,omitempty"`
	PriceMinorUnits int64                  `protobuf:"varint,8,opt,name=price_minor_units,json=priceMinorUnits,proto3" json:"price_minor_units,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Rating          int32                  `protobuf:"varint,10,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment         string                 `protobuf:"bytes,11,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Order) GetTaxiType() TaxiType {
	if x != nil {
		return x.TaxiType
	}
	return TaxiType_TAXI_TYPE_UNSPECIFIED
}

func (x *Order) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Order) GetDestination() *Location {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Order) GetPriceMinorUnits() int64 {
	if x != nil {
		return x.PriceMinorUnits
	}
	return 0
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Order) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type StartTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripRequest) Reset() {
	*x = StartTripRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripRequest) ProtoMessage() {}

func (x *StartTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripRequest.ProtoReflect.Descriptor instead.
func (*StartTripRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *StartTripRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type StartTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripResponse) Reset() {
	*x = StartTripResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripResponse) ProtoMessage() {}

func (x *StartTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripResponse.ProtoReflect.Descriptor instead.
func (*StartTripResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *StartTripResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CompleteTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTripRequest) Reset() {
	*x = CompleteTripRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTripRequest) ProtoMessage() {}

func (x *CompleteTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTripRequest.ProtoReflect.Descriptor instead.
func (*CompleteTripRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteTripRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type CompleteTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTripResponse) Reset() {
	*x = CompleteTripResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTripResponse) ProtoMessage() {}

func (x *CompleteTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTripResponse.ProtoReflect.Descriptor instead.
func (*CompleteTripResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *CompleteTripResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type RateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateTripRequest) Reset() {
	*x = RateTripRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateTripRequest) ProtoMessage() {}

func (x *RateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateTripRequest.ProtoReflect.Descriptor instead.
func (*RateTripRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{9}
}

func (x *RateTripRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *RateTripRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *RateTripRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type RateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateTripResponse) Reset() {
	*x = RateTripResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateTripResponse) ProtoMessage() {}

func (x *RateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateTripResponse.ProtoReflect.Descriptor instead.
func (*RateTripResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{10}
}

func (x *RateTripResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long          float64                `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_order_service_order_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_shared_proto_order_service_order_service_proto_rawDescGZIP(), []int{15}
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLong() float64 {
	if x != nil {
		return x.Long
	}
	return 0
}

var File_shared_proto_order_service_order_service_proto protoreflect.FileDescriptor

const file_shared_proto_order_service_order_service_proto_rawDesc = "" +
	"\n" +
	".shared/proto/order_service/order_service.proto\x12\border.v1\x1a\x1cgoogle/api/annotations.proto\"\xa5\x01\n" +
	"\x12CreateOrderRequest\x12/\n" +
	"\ttaxi_type\x18\x01 \x01(\x0e2\x12.order.v1.TaxiTypeR\btaxiType\x12(\n" +
	"\x05start\x18\x02 \x01(\v2\x12.order.v1.LocationR\x05start\x124\n" +
	"\vdestination\x18\x03 \x01(\v2\x12.order.v1.LocationR\vdestination\"\x85\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\x12/\n" +
	"\ttaxi_type\x18\x04 \x01(\x0e2\x12.order.v1.TaxiTypeR\btaxiType\x12(\n" +
	"\x05start\x18\x05 \x01(\v2\x12.order.v1.LocationR\x05start\x124\n" +
	"\vdestination\x18\x06 \x01(\v2\x12.order.v1.LocationR\vdestination\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.order.v1.StatusR\x06status\x12*\n" +
	"\x11price_minor_units\x18\b \x01(\x03R\x0fpriceMinorUnits\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06rating\x18\n" +
	" \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\v \x01(\tR\acomment\"<\n" +
	"\x13CreateOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"/\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"<\n" +
	"\x13CancelOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"-\n" +
	"\x10StartTripRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\":\n" +
	"\x11StartTripResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"0\n" +
	"\x13CompleteTripRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"=\n" +
	"\x14CompleteTripResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"^\n" +
	"\x0fRateTripRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"9\n" +
	"\x10RateTripResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"A\n" +
	"\x11ListOrdersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"S\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"0\n" +
	"\bLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x12\n" +
	"\x04long\x18\x02 \x01(\x01R\x04long*k\n" +
	"\bTaxiType\x12\x19\n" +
	"\x15TAXI_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TAXI_TYPE_ECONOMY\x10\x01\x12\x15\n" +
	"\x11TAXI_TYPE_COMFORT\x10\x02\x12\x16\n" +
	"\x12TAXI_TYPE_BUSINESS\x10\x03*\x94\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CREATED\x10\x01\x12\x1a\n" +
	"\x16STATUS_DRIVER_ASSIGNED\x10\x02\x12\x16\n" +
	"\x12STATUS_IN_PROGRESS\x10\x03\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x052\xee\x05\n" +
	"\fOrderService\x12a\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/orders\x12p\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1d.order.v1.CancelOrderResponse\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/v1/orders/{order_id}/cancel\x12i\n" +
	"\tStartTrip\x12\x1a.order.v1.StartTripRequest\x1a\x1b.order.v1.StartTripResponse\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/v1/orders/{order_id}/start\x12u\n" +
	"\fCompleteTrip\x12\x1d.order.v1.CompleteTripRequest\x1a\x1e.order.v1.CompleteTripResponse\"&\x82\xd3\xe4\x93\x02 \"\x1e/v1/orders/{order_id}/complete\x12h\n" +
	"\bRateTrip\x12\x19.order.v1.RateTripRequest\x1a\x1a.order.v1.RateTripResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/orders/{order_id}/rate\x12`\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/orders/{order_id}\x12[\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/ordersBUZSgithub.com/aleksiaichuk-innowise/inno_taxi/shared/proto/order_service;order_serviceb\x06proto3"

var (
	file_shared_proto_order_service_order_service_proto_rawDescOnce sync.Once
	file_shared_proto_order_service_order_service_proto_rawDescData []byte
)

func file_shared_proto_order_service_order_service_proto_rawDescGZIP() []byte {
	file_shared_proto_order_service_order_service_proto_rawDescOnce.Do(func() {
		file_shared_proto_order_service_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_order_service_proto_rawDesc), len(file_shared_proto_order_service_order_service_proto_rawDesc)))
	})
	return file_shared_proto_order_service_order_service_proto_rawDescData
}

var file_shared_proto_order_service_order_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shared_proto_order_service_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_shared_proto_order_service_order_service_proto_goTypes = []any{
	(TaxiType)(0),                // 0: order.v1.TaxiType
	(Status)(0),                  // 1: order.v1.Status
	(*CreateOrderRequest)(nil),   // 2: order.v1.CreateOrderRequest
	(*Order)(nil),                // 3: order.v1.Order
	(*CreateOrderResponse)(nil),  // 4: order.v1.CreateOrderResponse
	(*CancelOrderRequest)(nil),   // 5: order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),  // 6: order.v1.CancelOrderResponse
	(*StartTripRequest)(nil),     // 7: order.v1.StartTripRequest
	(*StartTripResponse)(nil),    // 8: order.v1.StartTripResponse
	(*CompleteTripRequest)(nil),  // 9: order.v1.CompleteTripRequest
	(*CompleteTripResponse)(nil), // 10: order.v1.CompleteTripResponse
	(*RateTripRequest)(nil),      // 11: order.v1.RateTripRequest
	(*RateTripResponse)(nil),     // 12: order.v1.RateTripResponse
	(*GetOrderRequest)(nil),      // 13: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),     // 14: order.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),    // 15: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),   // 16: order.v1.ListOrdersResponse
	(*Location)(nil),             // 17: order.v1.Location
}
var file_shared_proto_order_service_order_service_proto_depIdxs = []int32{
	0,  // 0: order.v1.CreateOrderRequest.taxi_type:type_name -> order.v1.TaxiType
	17, // 1: order.v1.CreateOrderRequest.start:type_name -> order.v1.Location
	17, // 2: order.v1.CreateOrderRequest.destination:type_name -> order.v1.Location
	0,  // 3: order.v1.Order.taxi_type:type_name -> order.v1.TaxiType
	17, // 4: order.v1.Order.start:type_name -> order.v1.Location
	17, // 5: order.v1.Order.destination:type_name -> order.v1.Location
	1,  // 6: order.v1.Order.status:type_name -> order.v1.Status
	3,  // 7: order.v1.CreateOrderResponse.order:type_name -> order.v1.Order
	3,  // 8: order.v1.CancelOrderResponse.order:type_name -> order.v1.Order
	3,  // 9: order.v1.StartTripResponse.order:type_name -> order.v1.Order
	3,  // 10: order.v1.CompleteTripResponse.order:type_name -> order.v1.Order
	3,  // 11: order.v1.RateTripResponse.order:type_name -> order.v1.Order
	3,  // 12: order.v1.GetOrderResponse.order:type_name -> order.v1.Order
	3,  // 13: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	2,  // 14: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	5,  // 15: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	7,  // 16: order.v1.OrderService.StartTrip:input_type -> order.v1.StartTripRequest
	9,  // 17: order.v1.OrderService.CompleteTrip:input_type -> order.v1.CompleteTripRequest
	11, // 18: order.v1.OrderService.RateTrip:input_type -> order.v1.RateTripRequest
	13, // 19: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	15, // 20: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	4,  // 21: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	6,  // 22: order.v1.OrderService.CancelOrder:output_type -> order.v1.CancelOrderResponse
	8,  // 23: order.v1.OrderService.StartTrip:output_type -> order.v1.StartTripResponse
	10, // 24: order.v1.OrderService.CompleteTrip:output_type -> order.v1.CompleteTripResponse
	12, // 25: order.v1.OrderService.RateTrip:output_type -> order.v1.RateTripResponse
	14, // 26: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	16, // 27: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_shared_proto_order_service_order_service_proto_init() }
func file_shared_proto_order_service_order_service_proto_init() {
	if File_shared_proto_order_service_order_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_order_service_order_service_proto_rawDesc), len(file_shared_proto_order_service_order_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_order_service_order_service_proto_goTypes,
		DependencyIndexes: file_shared_proto_order_service_order_service_proto_depIdxs,
		EnumInfos:         file_shared_proto_order_service_order_service_proto_enumTypes,
		MessageInfos:      file_shared_proto_order_service_order_service_proto_msgTypes,
	}.Build()
	File_shared_proto_order_service_order_service_proto = out.File
	file_shared_proto_order_service_order_service_proto_goTypes = nil
	file_shared_proto_order_service_order_service_proto_depIdxs = nil
}
