apiVersion: v1
kind: Secret
metadata:
  name: {{include "inno-taxi.fullname" . }}-secrets
  labels:
    {{ include "inno-taxi.labels" . | nindent 4}}
type:  Opaque
stringData:
  mongoRootUser: {{ .Values.credentials.mongoRootUser | quote }}
  mongoRootPassword: {{ .Values.credentials.mongoRootPassword | quote }}
  jwtSecret: {{ .Values.credentials.jwtSecret | quote }}
  pgOrderUser: {{ .Values.credentials.pgOrderUser | quote }}
  pgOrderPass: {{ .Values.credentials.pgOrderPass | quote }}
  pgWalletUser: {{ .Values.credentials.pgWalletUser | quote }}
  pgWalletPass: {{ .Values.credentials.pgWalletPass | quote }}
  clickhouseUsername: {{ .Values.credentials.clickhouseUsername | quote }}
  clickhousePassword: {{ .Values.credentials.clickhousePassword | quote }}