apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  labels:
    {{- include "inno-taxi.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      {{- include "inno-taxi.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: clickhouse
  template:
    metadata:
      labels:
        {{- include "inno-taxi.labels" . | nindent 8 }}
        app.kubernetes.io/component: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8-alpine
          ports:
            - containerPort: 8123
              name: http
            - containerPort: 9000
              name: native
          env:
            - name: CLICKHOUSE_DB
              value: "analytics"
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "inno-taxi.fullname" . }}-secrets
                  key: clickhouseUsername
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "inno-taxi.fullname" . }}-secrets
                  key: clickhousePassword
          volumeMounts:
            - name: clickhouse-data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d/listen-ipv4.xml
              subPath: listen-ipv4.xml
      volumes:
        - name: config
          configMap:
            name: clickhouse-listen-ipv4
  volumeClaimTemplates:
    - metadata:
        name: clickhouse-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    {{- include "inno-taxi.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
      name: http
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: native
  selector:
    {{- include "inno-taxi.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse