// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: shared/proto/user_service/kafka.proto

package user_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRegisteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisteredEvent) Reset() {
	*x = UserRegisteredEvent{}
	mi := &file_shared_proto_user_service_kafka_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisteredEvent) ProtoMessage() {}

func (x *UserRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_user_service_kafka_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisteredEvent.ProtoReflect.Descriptor instead.
func (*UserRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_user_service_kafka_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisteredEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegisteredEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserRegisteredEvent) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisteredEvent) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserRegisteredEvent) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserRegisteredEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_shared_proto_user_service_kafka_proto protoreflect.FileDescriptor

const file_shared_proto_user_service_kafka_proto_rawDesc = "" +
	"\n" +
	"%shared/proto/user_service/kafka.proto\x12\ruser.kafka.v1\"\xa1\x01\n" +
	"\x13UserRegisteredEvent\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtBSZQgithub.com/aleksiaichuk-innowise/inno_taxi/shared/proto/user_service;user_serviceb\x06proto3"

var (
	file_shared_proto_user_service_kafka_proto_rawDescOnce sync.Once
	file_shared_proto_user_service_kafka_proto_rawDescData []byte
)

func file_shared_proto_user_service_kafka_proto_rawDescGZIP() []byte {
	file_shared_proto_user_service_kafka_proto_rawDescOnce.Do(func() {
		file_shared_proto_user_service_kafka_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_user_service_kafka_proto_rawDesc), len(file_shared_proto_user_service_kafka_proto_rawDesc)))
	})
	return file_shared_proto_user_service_kafka_proto_rawDescData
}

var file_shared_proto_user_service_kafka_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_shared_proto_user_service_kafka_proto_goTypes = []any{
	(*UserRegisteredEvent)(nil), // 0: user.kafka.v1.UserRegisteredEvent
}
var file_shared_proto_user_service_kafka_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shared_proto_user_service_kafka_proto_init() }
func file_shared_proto_user_service_kafka_proto_init() {
	if File_shared_proto_user_service_kafka_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_user_service_kafka_proto_rawDesc), len(file_shared_proto_user_service_kafka_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_user_service_kafka_proto_goTypes,
		DependencyIndexes: file_shared_proto_user_service_kafka_proto_depIdxs,
		MessageInfos:      file_shared_proto_user_service_kafka_proto_msgTypes,
	}.Build()
	File_shared_proto_user_service_kafka_proto = out.File
	file_shared_proto_user_service_kafka_proto_goTypes = nil
	file_shared_proto_user_service_kafka_proto_depIdxs = nil
}
